In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
veriler = pd.read_csv("Churn_Modelling.csv")
veriler

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
X = veriler.iloc[:,3:13].values
Y = veriler.iloc[:,13].values

In [43]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

In [44]:
le2 = preprocessing.LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2])

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe = ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder="passthrough")
X = ohe.fit_transform(X)
X = X[:,1:]

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.33, random_state = 0)

In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

YAPAY ZEKA

In [48]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [49]:
classifier = Sequential()
classifier.add(Dense(6, activation="relu", input_dim = 11))

classifier.add(Dense(6, activation="relu"))

classifier.add(Dense(1, activation="sigmoid"))

In [58]:
classifier.compile(optimizer = "adam",loss = "binary_crossentropy", metrics=["accuracy"])
classifier.fit(X_train,y_train, epochs=50)
y_pred = classifier.predict(X_test)

Epoch 1/50
210/210 [==============================] - 1s 822us/step - loss: 0.6488 - accuracy: 0.6533
Epoch 2/50
210/210 [==============================] - 0s 863us/step - loss: 0.4972 - accuracy: 0.7949
Epoch 3/50
210/210 [==============================] - 0s 898us/step - loss: 0.4570 - accuracy: 0.8048
Epoch 4/50
210/210 [==============================] - 0s 937us/step - loss: 0.4346 - accuracy: 0.8084
Epoch 5/50
210/210 [==============================] - 0s 803us/step - loss: 0.4193 - accuracy: 0.8127
Epoch 6/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4060 - accuracy: 0.8190
Epoch 7/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3928 - accuracy: 0.8266
Epoch 8/50
210/210 [==============================] - 0s 975us/step - loss: 0.3802 - accuracy: 0.8357
Epoch 9/50
210/210 [==============================] - 0s 937us/step - loss: 0.3699 - accuracy: 0.8436
Epoch 10/50
210/210 [==============================] - 0s 870us/step - loss: 0.3632 - accuracy: 0.8479
Epoch 11/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8513
Epoch 12/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3556 - accuracy: 0.8527
Epoch 13/50
210/210 [==============================] - 0s 879us/step - loss: 0.3536 - accuracy: 0.8551
Epoch 14/50
210/210 [==============================] - 0s 867us/step - loss: 0.3522 - accuracy: 0.8560
Epoch 15/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8566
Epoch 16/50
210/210 [==============================] - 0s 939us/step - loss: 0.3499 - accuracy: 0.8597
Epoch 17/50
210/210 [==============================] - 0s 879us/step - loss: 0.3486 - accuracy: 0.8612
Epoch 18/50
210/210 [==============================] - 0s 937us/step - loss: 0.3476 - accuracy: 0.8596
Epoch 19/50
210/210 [==============================] - 0s 860us/step - loss: 0.3467 - accuracy: 0.8607
Epoch 20/50
210/210 [==============================] - 0s 864us/step - loss: 0.3454 - accuracy: 0.8613
Epoch 21/50
210/210 [==============================] - 0s 975us/step - loss: 0.3447 - accuracy: 0.8607
Epoch 22/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8606
Epoch 23/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3438 - accuracy: 0.8594
Epoch 24/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3435 - accuracy: 0.8625
Epoch 25/50
210/210 [==============================] - 0s 900us/step - loss: 0.3430 - accuracy: 0.8622
Epoch 26/50
210/210 [==============================] - 0s 960us/step - loss: 0.3427 - accuracy: 0.8625
Epoch 27/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3419 - accuracy: 0.8610
Epoch 28/50
210/210 [==============================] - 0s 995us/step - loss: 0.3417 - accuracy: 0.8621
Epoch 29/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3414 - accuracy: 0.8634
Epoch 30/50
210/210 [==============================] - 0s 937us/step - loss: 0.3408 - accuracy: 0.8619
Epoch 31/50
210/210 [==============================] - 0s 939us/step - loss: 0.3402 - accuracy: 0.8622
Epoch 32/50
210/210 [==============================] - 0s 900us/step - loss: 0.3398 - accuracy: 0.8639
Epoch 33/50
210/210 [==============================] - 0s 975us/step - loss: 0.3393 - accuracy: 0.8624
Epoch 34/50
210/210 [==============================] - 0s 899us/step - loss: 0.3391 - accuracy: 0.8630
Epoch 35/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8625
Epoch 36/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8630
Epoch 37/50
210/210 [==============================] - 0s 959us/step - loss: 0.3380 - accuracy: 0.8625
Epoch 38/50
210/210 [==============================] - 0s 937us/step - loss: 0.3373 - accuracy: 0.8640
Epoch 39/50
210/210 [==============================] - 0s 975us/step - loss: 0.3367 - accuracy: 0.8645
Epoch 40/50
210/210 [==============================] - 0s 938us/step - loss: 0.3369 - accuracy: 0.8627
Epoch 41/50
210/210 [==============================] - 0s 921us/step - loss: 0.3365 - accuracy: 0.8637
Epoch 42/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8628
Epoch 43/50
210/210 [==============================] - 0s 957us/step - loss: 0.3359 - accuracy: 0.8634
Epoch 44/50
210/210 [==============================] - 0s 898us/step - loss: 0.3355 - accuracy: 0.8631
Epoch 45/50
210/210 [==============================] - 0s 899us/step - loss: 0.3358 - accuracy: 0.8631
Epoch 46/50
210/210 [==============================] - 0s 900us/step - loss: 0.3357 - accuracy: 0.8637
Epoch 47/50
210/210 [==============================] - 0s 898us/step - loss: 0.3354 - accuracy: 0.8636
Epoch 48/50
210/210 [==============================] - 0s 862us/step - loss: 0.3349 - accuracy: 0.8645
Epoch 49/50
210/210 [==============================] - 0s 898us/step - loss: 0.3348 - accuracy: 0.8625
Epoch 50/50
210/210 [==============================] - 0s 847us/step - loss: 0.3349 - accuracy: 0.8636
104/104 [==============================] - 0s 681us/step

In [59]:
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2510,  107],
       [ 360,  323]], dtype=int64)